### ISSUE TITLE
base16 shell triger i3

### ISSUE THREAD

**Issue by alobaid** [khamer/base16-i3#1]
#enhancement
You could also add to the profile_helper.sh in base16-shell after adding the colors to .config/i3/colors
```sh
if [ -f $HOME/.config/i3/colors/base16-$theme.config ]; then                                       
    cat $HOME/.config/i3/colors/base16-$theme.config \                           
       $HOME/.config/i3/config.base > $HOME/.config/i3/config                    
     i3-msg reload                                                                
     fi                                                                             
 }  
```
Now when you change the shell & i3 :)

**Comment by khamer** [comment]
[base16-shell](https://github.com/chriskempson/base16-shell) is managed by chriskempson and not me, so you'd have to ask about getting it add to that repo instead. Neat thought though!
