### ISSUE TITLE
Where are the themes?

### ISSUE THREAD

**Issue by i-oliva** [khamer/base16-i3#7]
Hi, since the last commit every theme has disappeared? Where is it?

**Comment by khamer** [comment]
Hrm, I'll look into it, it looks like the new mustache includes didn't work at all.

**Comment by i-oliva** [comment]
Thanks! btw is there any "old" branch available while you look into that?

**Comment by khamer** [comment]
No - you'd just have to back up a commit. I believe it's fixed now anyway - it looks like using partials doesn't work properly, at least with the chriskempson/base16-builder-php builder.
