### ISSUE TITLE
please merge from latest base16

### ISSUE THREAD

**Issue by steinex** [khamer/base16-i3#8]
Hi,

could you get the repo updated from latest base16? In the meantime there are a number of new themes i really would like to have in base-i3.

Thanks!

**Comment by JamyGolden** [comment]
We've just merged a change where a bot builds the latest schemes every week, so we'll always be up to date :smile: https://github.com/base16-project/base16-i3/commit/7fa529ca44bf749c0791abc0e1797edd21dae692
